### PR TITLE
Fix the python model empty/sample mode fix to not break when the ref macro has been overridden

### LINKED ISSUE #953: [BUG] Python models break when the `ref` macro has been overridden to return a string
## Problem
In #911 (fix for #906) we altered the python.sql template for python models such that `.render()` would be called on refs in order to skip the extra filtering that happens on them in empty and sample mode. This was necessary because the extra filtering was breaking python models. However, people are known to override the `ref` macro, and sometimes in doing so change the return type of `ref` such that instead of returning a `<Adapter>Relation` object, they return a string. The problem with this is that strings do not have `.render()` method. Thus a new error cropped up in that looked something like

```
  Compilation Error in model my_python_model(models/mart/my_python_model.py)
    'str object' has no attribute 'render'
    
    > in macro py_script_postfix (macros/python_model/python.sql)
    > called by model my_python_model (models/mart/my_python_model.py)"
```

## Desired fix
1. We don't break when `ref()` returns a string
2. We still skip rendering the filtered statement in sample/empty mode

### PR DESCRIPTION
**Pull request by QMalcolm**
resolves #953
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#

### Problem

We broke python models for people who had overridden the `ref` macro to return a string.

### Solution

Only call `render()` on the resolved `ref()` if the thing returned from `ref()` isn't a `string`.

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [X] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt-adapters/src/dbt/include/global_project/macros/python_model/python.sql [hunk 1]
```diff
@@ -11,7 +11,17 @@
...
         {% set _ref_args = [_ref.get('package'), _ref['name']] if _ref.get('package') else [_ref['name'],] %}
-        {%- set resolved = ref(*_ref_args, v=_ref.get('version')).render() -%}
+        {%- set resolved = ref(*_ref_args, v=_ref.get('version')) -%}
+
+        {#
+            We want to get the string of the returned relation in order to skip sample/empty mode rendering logic.
+            However, people override the default ref macro, and often return a string instead of a relation. Thus,
+            to make sure we dont blow things up, we have ot ensure the resolved relation is not already a string.
+        #}
+        {%- if resolved is not string -%}
```
Comment (aranke) [inline dbt-adapters/src/dbt/include/global_project/macros/python_model/python.sql:21]: To be more defensive, maybe we should check if the `render` method is defined on the object instead?

**Review by aranke — APPROVED** [review]
LGTM!

**Review by mikealfare — APPROVED** [review]
