### PR TITLE
Better handling of invalid columns in models during persist_docs

### LINKED ISSUE #1690: [CT-1024] [Bug] Nonexistent column in yml file causes "can't execute an empty query"
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run dbt run  on table.sql and table.yml has a column and a test defined on a nonexistent column I get this error:

"can't execute an empty query"

### Expected Behavior

An error message stating "Non-existent column in table.yml. Please remove the column "column1" from the yml file. "

### Steps To Reproduce

with a table1.sql file with a simple select and a few ctes and 
with a table1.yml file with a non-existent column in table1.sql final select

```
run dbt run --select table1.sql
```

### Relevant log output

```shell
22:46:04  Database Error in model table1 (models/mart/tbl/table1.sql)
22:46:04    can't execute an empty query
22:46:04    compiled SQL at target/run/mlp_dbt/models/tbl/fct/table1.sql
```

### Environment

```markdown
- OS: docker python:3.9-slim
- Python: python:3.9-slim
- dbt:1.2
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sriramr98**
resolves dbt-labs/dbt-adapters#1690

### Problem

When we have a model with `persist_docs` enabled  with an invalid column, dbt fails with an error `can't execute an empty query`. 

This happens because we try to use `ALTER COLUMN` to add comment on the column since it doesn't exist in the model.

### Solution

We will gracefully handle this by warning users about the invalid column but letting the model build successfully since this only happens when we use `persist_docs` to document the column.

Screenshot 2026-02-27 at 8 25 52 PM

NOTE: The warning isn't very legible since there's no indicator that it's a warning. This is being handled in a separate [PR](https://github.com/dbt-labs/dbt-core/pull/12555) to improve warning messages

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql [hunk 1]
```diff
@@ -22,12 +22,36 @@
   {{ return(adapter.dispatch('persist_docs', 'dbt')(relation, model, for_relation, for_columns)) }}
 {% endmacro %}
 
+{#-- Validates documented columns against the actual database columns. Warns about any columns in column_dict that don't exist in existing_column_names. Returns a filtered column_dict containing only columns that exist. --#}
+{% macro validate_doc_columns(relation, column_dict, existing_column_names) %}
```
Comment (colin-k-rogers) [inline dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:26]: Can we move this to use the dispatch + default pattern?

File: dbt-spark/dagger/run_dbt_spark_tests.py [hunk 2]
```diff
@@ -9,6 +9,11 @@
 from dotenv import find_dotenv, load_dotenv
 
 PG_PORT = 5432
+# Resolve absolute paths to sibling packages (Dagger blocks relative ".." paths)
```
Comment (colin-k-rogers) [inline dbt-spark/dagger/run_dbt_spark_tests.py:12]: these seem unrelated to the PR's focus?

File: dbt-athena/src/dbt/include/athena/macros/adapters/persist_docs.sql [hunk 3]
```diff
@@ -1,6 +1,10 @@
 {% macro athena__persist_docs(relation, model, for_relation=true, for_columns=true) -%}
   {% set persist_relation_docs = for_relation and config.persist_relation_docs()%}
   {% set persist_column_docs = for_columns and config.persist_column_docs() and model.columns %}
+  {% if persist_column_docs %}
+    {% set existing_columns = adapter.get_columns_in_relation(relation) | map(attribute="name") | list %}
+    {% do validate_doc_columns(relation, model.columns, existing_columns) %}
```
Comment (colin-k-rogers) [inline dbt-athena/src/dbt/include/athena/macros/adapters/persist_docs.sql:6]: Why doesn't this follow the same pattern as the others and `{% set filtered_columns =...`?

File: dbt-postgres/src/dbt/include/postgres/macros/adapters.sql [hunk 4]
```diff
@@ -206,8 +206,7 @@
 
 
 {% macro postgres__alter_column_comment(relation, column_dict) %}
-  {% set existing_columns = adapter.get_columns_in_relation(relation) | map(attribute="name") | list %}
```
Comment (colin-k-rogers) [inline dbt-postgres/src/dbt/include/postgres/macros/adapters.sql:209]: this will break anyone with a custom materialization that relies on this current behavior. If we were to cache the `get_columns_in_relation` we could keep this as is with out requiring a second call

File: dbt-athena/src/dbt/include/athena/macros/adapters/persist_docs.sql (hunk 3 above)
Comment (sriramr98) [reply dbt-athena/src/dbt/include/athena/macros/adapters/persist_docs.sql:6]: We don't need to send in `filtered_columns` since it's being [handled](https://github.com/dbt-labs/dbt-adapters/blob/89cf3badd5ff8687addf50dedeb4be0a1c81e949/dbt-athena/src/dbt/adapters/athena/impl.py#L1084) in `persist_docs_to_glue` already.

We still call `validate_doc_columns` to warn the user. Any invalid columns are handled in `persist_docs_to_glue` method

File: dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql (hunk 1 above)
Comment (sriramr98) [reply dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:26]: We can. I just didn't see any reason someone would want to override this since it's pure logic with no interaction with adapters etc. If you think we should make it configurable, I will move this to using dispatch + default pattern.

File: dbt-spark/dagger/run_dbt_spark_tests.py (hunk 2 above)
Comment (sriramr98) [reply dbt-spark/dagger/run_dbt_spark_tests.py:12]: Yes, it's not related to the PR feature, but is required to test the changes in the PR reliably in our CI.

In the current setup, `dbt-adapters` and `dbt-tests-adapters` gets installed from the main branch. However, it won't work when running CI tests since we would have PRs like this one where there are changes in `dbt-adapters` and `dbt-test-adapter` that's required in-order to execute tests properly. I could raise a separate PR for this, but the change was small enough and was required in this PR to successfully run tests, I pushed it here.

Do you want me to raise a separate PR for this?

**Review by colin-k-rogers — APPROVED** [review]

File: dbt-spark/dagger/run_dbt_spark_tests.py (hunk 2 above)
Comment (colin-k-rogers) [reply dbt-spark/dagger/run_dbt_spark_tests.py:12]: let's leave it here, thanks for clarifying!

File: dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql [hunk 5]
```diff
@@ -22,12 +22,36 @@
...
+  {% set existing_lower = existing_column_names | map("lower") | list %}
```
Comment (xuliangs) [inline dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:27]: Do we need to consider quoting config here before deciding whether we can do case-insensitive comparison?

File: dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql [hunk 6]
```diff
@@ -22,12 +22,36 @@
...
+{% endmacro %}
+
 {% macro default__persist_docs(relation, model, for_relation, for_columns) -%}
   {% if for_relation and config.persist_relation_docs() and model.description %}
     {% do run_query(alter_relation_comment(relation, model.description)) %}
   {% endif %}
 
   {% if for_columns and config.persist_column_docs() and model.columns %}
-    {% do run_query(alter_column_comment(relation, model.columns)) %}
+    {% set existing_columns = adapter.get_columns_in_relation(relation) | map(attribute="name") | list %}
```
Comment (xuliangs) [inline dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:50]: I think this will introduce a redundant `get_columns_in_relation` for snowflake.
Snowflake uses `default__persist_docs` -> `alter_column_comment` -> `snowflake__alter_column_comment` which inside uses `get_columns_in_relation` already

Comment (sriramr98) [reply dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:50]: Yes @xuliangs . I discussed this with @colin-rogers-dbt when this PR was in play. Here's a TLDR;

1. We can move the `get_columns_in_relation` outside `snowflake__alter_column_comment` but that'll break the contract of `alter_column_comment`. We will need to pass in `existing_columns` from outside `alter_column_comment`. If any customer has custom macro overriding `alter_column_comment`, it'll be problematic. We had [this](https://github.com/dbt-labs/dbt-adapters/pull/1684#discussion_r2938062345) discussion regarding postgres, but the same applies here.

2. We looked at the performance overhead and decided that for the adapters which had the extra `get_columns_in_relation` , the latency cost isn't that high and is only applicable here when `persist_docs` is enabled, so we were okay with the extra metadata call.

Comment (xuliangs) [reply dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:50]: I didn't mean that we should move `get_columns_in_relation ` outside `snowflake__alter_column_comment `. Instead, we could either leave the `default__persist_docs` at it was, had the fix go into `redshift__persist_docs`, and `postgres__persist_docs` etc or we may create a override for snowflake without this extra call

Comment (xuliangs) [reply dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:50]: > We looked at the performance overhead and decided that for the adapters which had the extra get_columns_in_relation , the latency cost isn't that high and is only applicable here when persist_docs is enabled, so we were okay with the extra metadata call.

The issue that the PR is supposed to fix was for Redshift, Postgres, there was no problem for Snowflake, so the fix should be scoped to them as well. Besides we should always be diligent to avoid any unnecessary work, not to mention that this is one extra network call.

File: dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql (hunk 5 above)
Comment (jasonlin45) [reply dbt-adapters/src/dbt/include/global_project/macros/adapters/persist_docs.sql:27]: ^ yes this is a bug @sriramr98 https://docs.snowflake.com/en/sql-reference/identifiers-syntax

By default in Snowflake column identifiers are case sensitive when quoted.
fine for dbx and bq. redshift is configurable too.
