### PR TITLE
Fix snapshot type mismatch when new column added with hard_deletes=new_record

### LINKED ISSUE #852: [Bug] Snapshot fails to handle new column in source table
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Which packages are affected?

- [ ] dbt-adapters
- [ ] dbt-tests-adapter
- [x] dbt-athena
- [ ] dbt-athena-community
- [ ] dbt-bigquery
- [ ] dbt-postgres
- [ ] dbt-redshift
- [ ] dbt-snowflake
- [ ] dbt-spark

### Current Behavior

Snapshot (using iceberg) fails when source table gets a new column added. Even if this column is not part of the check columns.

### Expected Behavior

The process should detect that snapshot is missing the new column and add the column (and fill with null for previous rows). As is available in the [source code](https://github.com/dbt-labs/dbt-adapters/blob/main/dbt-athena/src/dbt/include/athena/macros/materializations/snapshots/snapshot.sql#L176-L178).

### Steps To Reproduce

Creating a snapshot like so:

```
{% snapshot snapshot_fct_all_datasets_cardinality %}

{% set current_schema = target.schema ~ '_snapshots' %}
{% set surr_key = dbt_utils.generate_surrogate_key(['dataset', 'partprovider', 'partsubprovider']) %}

{{
   config(
       target_schema=current_schema,
       unique_key=surr_key,
       check_cols=['cardinality', 'dataset_checksum'],
       materialized='snapshot',
       table_type='iceberg',
       strategy='check',
       updated_at='updated_at',
       hard_deletes='new_record',
       post_hook=[
         "DELETE FROM {{ this }}
          WHERE (dataset, partprovider, partsubprovider, updated_at) 
            IN (
                    SELECT dataset, partprovider, partsubprovider, updated_at 
                    FROM 
                    (
                        SELECT dataset, partprovider, partsubprovider, updated_at, 
                        row_number() OVER (PARTITION BY dataset, partprovider, partsubprovider ORDER BY updated_at DESC) AS rn 
                        FROM {{ this }}
                    ) sub 
                    WHERE rn > 3
                )"
       ]
   )
}}

SELECT dataset,
    cardinality,
    max_onboarding_date,
    min_onboarding_date,
    dataset_checksum,
    updated_at,
    updated_at_prev,
    cardinality_bloom_change_prev_to_new,
    cardinality_change_prev_to_new,
    has_changed,
    partprovider,
    partsubprovider
    
from {{ref("fct_all_datasets_cardinality")}}


{% endsnapshot %}
```

then running `dbt snapshot`

works as expected

inlcuding running `dbt snapshot` again and again

however, when adding a new ccolumn to the snapshot (the column is definitely available in the source table, like so:

```
{% snapshot snapshot_fct_all_datasets_cardinality %}

{% set current_schema = target.schema ~ '_snapshots' %}
{% set surr_key = dbt_utils.generate_surrogate_key(['dataset', 'partprovider', 'partsubprovider']) %}

{{
   config(
       target_schema=current_schema,
       unique_key=surr_key,
       check_cols=['cardinality', 'dataset_checksum'],
       materialized='snapshot',
       table_type='iceberg',
       strategy='check',
       updated_at='updated_at',
       hard_deletes='new_record',
       post_hook=[
         "DELETE FROM {{ this }}
          WHERE (dataset, partprovider, partsubprovider, updated_at) 
            IN (
                    SELECT dataset, partprovider, partsubprovider, updated_at 
                    FROM 
                    (
                        SELECT dataset, partprovider, partsubprovider, updated_at, 
                        row_number() OVER (PARTITION BY dataset, partprovider, partsubprovider ORDER BY updated_at DESC) AS rn 
                        FROM {{ this }}
                    ) sub 
                    WHERE rn > 3
                )"
       ]
   )
}}

SELECT dataset,
    cardinality,
    cardinality_bloom,
    max_onboarding_date,
    min_onboarding_date,
    dataset_checksum,
    updated_at,
    updated_at_prev,
    cardinality_bloom_change_prev_to_new,
    cardinality_change_prev_to_new,
    has_changed,
    partprovider,
    partsubprovider
    
from {{ref("fct_all_datasets_cardinality")}}


{% endsnapshot %}
```

`cardinality_bloom` was added

### Relevant log output

```shell
we get:


 Runtime Error in snapshot snapshot_fct_all_datasets_cardinality (snapshots/snapshot_fct_all_datasets_cardinality_de_mocktest.sql)
  COLUMN_NOT_FOUND: line 102:6: Column 'snapshotted_data.cardinality_bloom' cannot be resolved or requester is not authorized to access requested resources.
```

### Environment

```markdown
14:50:56  Running with dbt=1.9.2
14:50:56  dbt version: 1.9.2
14:50:56  python version: 3.10.15
14:50:56  os info: macOS-15.3.1-arm64-arm-64bit
14:50:56  adapter type: athena
14:50:56  adapter version: 1.9.1
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aahel**
resolves #852

### Problem

When using `hard_deletes: new_record` snapshots, adding a new column to the source table causes the snapshot to fail. There are two distinct errors depending on the adapter:

**Athena, Snowflake, Databricks** — `snapshotted_data.<new_col>` not found (fixed by #1201):
```
invalid identifier 'SNAPSHOTTED_DATA.JOB_TITLE'
Column 'snapshotted_data.job_title' cannot be resolved
```

**BigQuery** — type mismatch in UNION ALL (this PR):
```
Column 5 in UNION ALL has incompatible types: STRING, STRING, STRING, INT64
```

Both errors occur in the `deletion_records` CTE, which creates a soft-delete record when a row is removed from the source. #1201 fixed the first class of errors by inserting bare `NULL` as a placeholder for new columns that don't yet exist in the snapshot table. However, on BigQuery, an untyped `NULL` defaults to `INT64`, which conflicts with the actual column type (e.g. `STRING`) in the other three arms of the UNION ALL (`insertions`, `updates`, `deletes`). Snowflake, Athena, and Databricks are lenient about untyped `NULL` in a UNION ALL and coerce it to the correct type — BigQuery is not.

### Solution

Use `cast(NULL as <data_type>)` instead of bare `NULL` for new column placeholders in the `deletion_records` CTE. The data type comes from `get_column_schema_from_query()`, which already knows each source column's type.

**Before:**
```sql
NULL as "job_title",
```

**After:**
```sql
cast(NULL as TEXT) as "job_title",
```

Also adds integration tests covering:
- Check strategy with `check_cols: all` + new column (existing test)
- Timestamp strategy + new column
- Check strategy with specific `check_cols` where new column is NOT in the check list (original #852 scenario)
- New column + deleted row simultaneously (exercises the `deletion_records` CTE — the critical test)

Verified passing on both **Snowflake** (4/4) and **BigQuery** (4/4).

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql [hunk 1]
```diff
@@ -185,7 +185,7 @@
             {%- if col.name in snapshotted_cols -%}
             snapshotted_data.{{ adapter.quote(col.column) }},
             {%- else -%}
-            NULL as {{ adapter.quote(col.column) }},
+            cast(NULL as {{ col.data_type }}) as {{ adapter.quote(col.column) }},
```
Comment (dbeatty10) [inline dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql]: @aahel I'd suggest using [this](https://github.com/dbt-labs/dbt-adapters/issues/1702#issuecomment-3987916966) because the [`safe_cast`](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#safe_cast) cross-database macro handles difficult edge cases in [snowflake](https://github.com/dbt-labs/dbt-adapters/blob/77a0fe310a8fdede88e14b19b4708ece1a18d518/dbt-snowflake/src/dbt/include/snowflake/macros/utils/safe_cast.sql#L4), [bigquery](https://github.com/dbt-labs/dbt-adapters/blob/77a0fe310a8fdede88e14b19b4708ece1a18d518/dbt-bigquery/src/dbt/include/bigquery/macros/utils/safe_cast.sql), etc.


```sql
  {{ safe_cast('NULL', col.dtype) }} as {{ adapter.quote(col.column) }},
```

```suggestion
            {{ safe_cast('NULL', col.dtype) }} as {{ adapter.quote(col.column) }},
```

Comment (aahel) [reply dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql]: fixed
